### PR TITLE
Reviewed project

### PR DESCRIPTION
**Pull request by zieeco**
## In this project, I; 

- Added the original version of the project in the index.html file.
- Styled the original version of the project in the style.css file.
- Added a readme file.
- Added a file that needed to be ignored in the .gitignore file.
- Ensured there was no liters error.

### CODE REVIEW

**Review by zieeco — COMMENTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi @zieeco,
Good job so far. 
There are still some issues you still need to work on in order to move to the next step. 

image

## Good points 👍 
- No Linters error ✔️ 
- I love your project, it's nice ✔️ 

## Aspects to improve ♻️

- [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by mricanho — APPROVED** [review]
# Status: ✔️ Project Approved ✔️ 

Hello @zieeco  🔥 

You are reviewing like a pro, good job👍🏽 

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zieeco** [comment]
This project has been approved already but it is still showing "Request review" on my dashboard and that's  why I am submitting for another review, maybe the status will change on my dashboard to "Submit"... I have mailed student success team, but they've done nothing yet.

**Review by Dipeshtwis — APPROVED** [review]
# Status: Approved ✔️

## Hi @zieeco,

**I made your project approved. Maybe It happens because of mistake done by previous code review. But the status should changed now.**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**


## Sorry for the inconvenience. :pray: :pray: 

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
