### PR TITLE
initial project version

### PR DESCRIPTION
**Pull request by zieeco**
Add index.html file.
Add style.css file.
Add .gitignore file.
Add linter file.
Add readme file.

### CODE REVIEW

**Review by bolah2009 — CHANGES_REQUESTED** [review]
Hi @zieeco , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

This project is about reviewing your own project. Currently, there's no review on the PR. Please go ahead and add your review. See https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/review_your_project.md for more details.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by zieeco** [comment]
# Status: ✔️ Project Approved ✔️ 

Hello @zieeco! 

**Hi Zieeco, I was testing your project and everything worked perfectly on my machine. 
There was no linters error and you also used the correct workflow. Also, you documented your repo in quite a professional way but you forgot to add a link to a live demo**


Now you can merge this branch 🚀 

### 💻 👩🏽‍💻 Happy Coding! 👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by krys2fa — CHANGES_REQUESTED** [review]
Hi @zieeco, 

Good job so far!
You used polite language in your code review as well as emojis which made your review more human-friendly.
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
You should have submitted a review in the Pull Request you opened by utilizing the "Review changes" feature from GitHub.

Also, remember to use the [GitHub inline comments feature](/microverse/guides/tse/code_review/code_review_guidelines_2_0/-/blob/master/ADD_LINK_TO_VIDEO_OR_ARTCILE) in case you have to leave review comments, in this case at least 2. 😃 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by zieeco — COMMENTED** [review]
Hello @zieeco! 

**Hi Zieeco, I was testing your project and everything worked perfectly on my machine. 
There was no linters error and you also used the correct workflow. Also, you documented your repo in quite a professional way but you forgot to add a link to a live demo**


Now you can merge this branch 🚀 

### 💻 👩🏽‍💻 Happy Coding! 👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by christianotieno — APPROVED** [review]
Hi @zieeco, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

- [ ] Please take time to look at this [lesson ](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request)on how to add inline comments in your reviews. In general, you did great!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
